apiVersion: v1
kind: Service
metadata:
  name: lab2-backend-service
spec:
  type: NodePort
  selector:
    app: lab2-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
