apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab2-backend
  template:
    metadata:
      labels:
        app: lab2-backend
    spec:
      containers:
        - name: lab2-backend
          image: lab2-backend:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
