apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab2-frontend
  template:
    metadata:
      labels:
        app: lab2-frontend
    spec:
      containers:
        - name: lab2-frontend
          image: lab2-frontend:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
